

/** This config.h was hand-written, NOT generated by configure/autoheader. This
 *  is because libserver uses automake, but I don't like automake and prefer
 *  not to use it. Luckily, libwebserver only needs it for HAVE_OPENSSL, and
 *  since p4sync doesn't need SSL, I can just make this file a no-op.
 *
 * - Ryan Barrett <p4sync@ryanb.org>
 */

/* SSL */
/* #undef HAVE_OPENSSL */
