/* config.h. Generated by configure. Stripped to the bare necessities
   (excluding iconv and, locale, and other character encoding stuff!) by Ryan,
   who hates autoconf. :P
 */

/* Version number of package */
#define MPC_VERSION "0.11.2"
